name: Python package build and publish

on:
  push:
    tags:
      - 'release-*'

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Extract release tag
      run: echo "VERSION=${GITHUB_REF#refs/tags/release-}" >> $GITHUB_ENV

    - name: Update version in setup.py and pyproject.toml
      run: |
        sed -i "s/version=.*,/version='${{ env.VERSION }}',/" setup.py
        sed -i "s/version = \".*\"/version = \"${{ env.VERSION }}\"/" pyproject.toml

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add setup.py pyproject.toml
        git commit -m "Update version to ${{ env.VERSION }}"
        git push origin HEAD:test_version_auto
